# Generated by Django 5.2.1 on 2025-06-04 10:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование типа')),
                ('mask_sn', models.CharField(default='', max_length=20, verbose_name='Маска серийного номера')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Серийный номер')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmenttype')),
            ],
            options={
                'unique_together': {('equipment_type', 'serial_number')},
            },
        ),
    ]
